AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 Instance
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: must be a valid EC2 instance type
  SubnetId:
    Type: String
    Default: subnet-0117a6d55e691c6b2
    AllowedValues:
    - subnet-0117a6d55e691c6b2
    - subnet-0e513fb9e4419d71d
    - subnet-08300ea23ab36c090
    - subnet-0c06af66a463c50f1
    ConstraintDescription: must be a valid SbunetID


Mappings: 
  RegionMap: 
    ap-northeast-1:
      hvm: "ami-0792756bc9edf3e63"
    ap-southeast-1:
      hvm: "ami-0162da29310cc18f6"


Description: Create EC2 Instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', hvm]
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 8
      Tags:
      - Key: Name
        Value: myInstance
