AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 Instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0792756bc9edf3e63
      InstanceType: t2.micro
